#
#
#
version: "3.7"

volumes:
  redis-data:

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

  web:
    command: "/opt/planorama/script/planorama_start.sh"
    image: 666959015006.dkr.ecr.us-west-2.amazonaws.com/planorama:main
    #image: balen/planorama:prod
    #image: carterhaugh/planorama:prod
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - type: tmpfs
        target: /app/tmp
      - /opt/chicago/etc/planorama:/config
    environment:
      - PGID=1005
      - PUID=1001
      - RAILS_ENV=production
      - NODE_ENV=production
    env_file:
      - "/opt/chicago/etc/hostname.env"
      - "/opt/chicago/etc/planorama.env"
      - "/opt/chicago/etc/planorama-overrides.env"
      - "/opt/chicago/etc/creds.env"
    depends_on:
      - redis
    links:
      - redis
    restart: always

  planorama-sidekiq:
    command: "/opt/planorama/script/planorama_sidekiq.sh"
    image: 666959015006.dkr.ecr.us-west-2.amazonaws.com/planorama:main
    #image: balen/planorama:prod
    #image: carterhaugh/planorama:prod
    volumes:
      - type: tmpfs
        target: /app/tmp
      - /opt/chicago/etc/planorama:/config
    environment:
      - PGID=1005
      - PUID=1001
      - RAILS_ENV=production
      - NODE_ENV=production
    env_file:
      - "/opt/chicago/etc/hostname.env"
      - "/opt/chicago/etc/planorama.env"
      - "/opt/chicago/etc/planorama-overrides.env"
      - "/opt/chicago/etc/creds.env"
    depends_on:
      - redis
    links:
      - redis
    restart: always

