#
# This is the dev version of the docker compose
#
# docker-compose -p plano-stag -f  docker-compose-staging.yml -f docker-compose-pg.yml up
#
version: "3.7"

volumes:
  redis-data:
  # box: {} # used for the bundler, persistent store between runs

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
  #
  # NOTE:
  # .enrc set ths env variables for
  #   DB_PORT
  #   POSTGRES_USER
  #   POSTGRES_PASSWORD
  #
  planorama:
    # image: planorama:production
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file:
      - .envrc
    environment:
      - DB_HOST=postgres
      - RAILS_ENV=staging
      - NODE_ENV=staging
    command: /opt/planorama/script/planorama_start.sh
    volumes:
      - type: tmpfs
        target: /opt/planorama/tmp
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links:
      - redis

  planorama-sidekiq:
    # image: planorama:production
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file:
      - .envrc
    environment:
      - DB_HOST=postgres
      - RAILS_ENV=staging
      - NODE_ENV=staging
    command: /opt/planorama/script/planorama_sidekiq.sh
    volumes:
      - type: tmpfs
        target: /opt/planorama/tmp
    depends_on:
      - redis
    links:
      - redis
