#
# This is the dev version of the docker compose
#
# docker-compose -f docker-compose.yml -f  docker-compose-dev.yml up
#
version: "3.7"

volumes:
  redis-data:

services:
  planorama-redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "36379:6379"

  # TODO: sidekiq
  planorama-sidekiq:
    image: planorama:latest
    build:
      context: .
      dockerfile: dockerfile
    # TODO: run sidekiq shell
    command:
    restart: always
    depends_on:
      - postgres
      - planorama-redis

  # The planner app server
  planorama:
    env_file:
      - .envrc
    # TODO: run planorama
    command:
    depends_on:
      - planorama-redis
    links:
      - planorama-redis
    volumes:
      - .:/opt/planorama
