#
#
#
version: "3.7"

volumes:
  pgdata:

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    env_file:
      - .envrc
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  #
  planorama:
    depends_on:
      - postgres
    links:
      - postgres

  # planorama-sidekiq:
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres
