#
# This is the dev version of the docker compose
# this is overlaid on the docket compose for dev environments
#
# docker-compose -f docker-compose.yml -f  docker-compose-dev.yml up
#
version: "3.7"

services:
  postgres:
    volumes:
      - pgdata:/var/lib/postgres:cached
  planorama:
    image: planorama:dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: /opt/planorama/script/planorama_start.sh
    volumes:
      - node_modules:/opt/planorama/node_modules
      - .:/opt/planorama
      - box:/var/bundler # this is used to store make the bundle update/install persistent between runs
      - type: tmpfs
        target: /opt/planorama/tmp
    links:
      - livereload
      - mailcatcher
    ports:
      - 3035:3035
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
  livereload:
    image: planorama:dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: /opt/planorama/script/livereload_start.sh
    ports:
      - 35729:35729
    volumes:
      - .:/opt/planorama
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  # worker:
  #   entrypoint: "script/docker_sidekiq_entry.sh"
  #   working_dir: /hack
  #   image: registry.gitlab.com/worldcon/wellington:latest
  #   depends_on:
  #     - web
  #     - postgres
  #     - redis
  #   env_file:
  #     .env
  #   restart: always
  #   volumes:
  #     - node_modules:/hack/node_modules  # Except node_modules folder which is exclusive to the container
  #     - ./:/hack                         # Mount current working directory to /hack for hacking :)
  #     - type: tmpfs
  #       target: /hack/tmp

# Simple volumes used for persistent storage
volumes:
  node_modules:
  box: {} # used for the bundler, persistent store between runs
